language: node_js

node_js:
  - "4.2"
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

addons:
  ssh_known_hosts:
  - 192.241.218.94

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Decrypt the key file using EVN variable on travis
  - openssl aes-256-cbc -K $encrypted_1ef380e2aca1_key -iv $encrypted_1ef380e2aca1_iv -in deploy_static.pem.enc -out deploy_static.pem -d

  # Install npmv3 because of postinstall bugs in npmv2:
  # See https://github.com/FormidableLabs/victory/issues/98
  - npm install -g npm@3

install:
  - npm install
  - node_modules/.bin/builder run install-selenium

script:
  - npm test
  - NODE_ENV=production node_modules/.bin/builder run build-static
  - ROWDY_SETTINGS=local.firefox node_modules/.bin/builder run test-func-static-prod
  - ROWDY_SETTINGS=local.phantomjs node_modules/.bin/builder run test-func-static-prod

# Once build on Travis is working, automatically deploy it on master only:
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
